project:
  type: website

website:
  title: "Edilene Cavalcanti"
  navbar:
    right:
      - text: "Posts"
        file: posts.qmd
      - text: "Materiais"
        file: materiais.qmd
      - sidebar:publicacoes
      - text: Currículo
        href: https://drive.google.com/file/d/12qjE68pUX9p1O7Bn6zTuSur2i2DIWcNp/view?usp=sharing
      - icon: github
        href: https://github.com/edilenecavalcanti

        
  sidebar:
    - id: publicacoes
      title: "Publicações"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
      - text: "Estudos"
        file: estudos.qmd
      - text: "Dashboards"
        file: dashboards.qmd
      sidebar: false
        
format:
  html:
    theme: 
      light: pulse
    css: styles.css
    toc: true

editor: visual

