project:
  type: website

website:
  title: "Edilene Cavalcanti"
  navbar:
    right:
      - sidebar:portfolio
      - text: "Posts"
        file: posts.qmd
      - text: "Materiais"
        file: materiais.qmd
      - text: "Anotações"
        file: anotacoes.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
        
  sidebar:
    - id: portfolio
      title: "Portfólio"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
      - text: "Estudos"
        file: estudos.qmd
      - text: "Dashboards"
        file: dashboards.qmd
      sidebar: false
        
format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

